import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { AuthUser, ChatChannel, ChatMessage, GameSummary } from "@oyna/contracts";
import { randomUUID } from "node:crypto"; import { DatabaseService } from "../database/database.service";
interface MessageRow { id:string;channel_id:string;author_id:string|null;nickname:string|null;avatar_url:string|null;text:string;reply_to_id:string|null;image_url:string|null;deleted_at:Date|null;created_at:Date; }
@Injectable() export class ChatService {
  private readonly messages:ChatMessage[]=[]; private readonly blocked=new Set<string>(); private readonly recent=new Map<string,number[]>();
  constructor(private readonly db:DatabaseService){}
  async games():Promise<GameSummary[]>{ if(!this.db.configured)return [{id:"cs2",slug:"cs2",name:"Counter-Strike 2",steamAppId:730,teamSize:5,active:true},{id:"dota2",slug:"dota-2",name:"Dota 2",steamAppId:570,teamSize:5,active:true},{id:"valorant",slug:"valorant",name:"VALORANT",teamSize:5,active:true}]; const r=await this.db.query<{id:string;slug:string;name:string;steam_app_id:number|null;team_size:number;active:boolean}>("SELECT * FROM games WHERE active ORDER BY name");return r.rows.map(x=>({id:x.id,slug:x.slug,name:x.name,steamAppId:x.steam_app_id??undefined,teamSize:x.team_size,active:x.active}));}
  async channels(city?:string):Promise<ChatChannel[]>{if(!this.db.configured){const games=await this.games();return games.flatMap(g=>[{id:`${g.id}-kz`,gameId:g.id,scope:"country" as const,name:`${g.name} · Казахстан`},...(city?[{id:`${g.id}-${city}`,gameId:g.id,scope:"city" as const,city,name:`${g.name} · ${city}`}]:[])]);}const r=await this.db.query<{id:string;game_id:string;scope:"country"|"city";city:string|null;name:string}>("SELECT id,game_id,scope,city,name FROM chat_channels WHERE scope='country' OR city=$1 ORDER BY game_id,scope",[city??""]);return r.rows.map(x=>({id:x.id,gameId:x.game_id,scope:x.scope,city:x.city??undefined,name:x.name}));}
  async list(channelId:string,userId:string,cursor?:string):Promise<ChatMessage[]>{if(!this.db.configured)return this.messages.filter(m=>m.channelId===channelId).slice(-50);const r=await this.db.query<MessageRow>(`SELECT m.*,u.nickname,u.avatar_url FROM chat_messages m LEFT JOIN users u ON u.id=m.author_id WHERE m.channel_id=$1 AND ($2::timestamptz IS NULL OR m.created_at<$2) AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$3 AND b.blocked_id=m.author_id) OR (b.blocker_id=m.author_id AND b.blocked_id=$3)) ORDER BY m.created_at DESC,m.id DESC LIMIT 50`,[channelId,cursor??null,userId]);return r.rows.reverse().map(this.map);}
  async create(channelId:string,user:AuthUser,body:{text:string;replyToId?:string;imageUrl?:string}):Promise<ChatMessage>{const text=body.text?.trim();if(!text||text.length>2000)throw new BadRequestException("Message must contain 1-2000 characters");if(body.imageUrl&&!/^https?:\/\//.test(body.imageUrl))throw new BadRequestException("Invalid image URL");this.rateLimit(user.id);const id=randomUUID(),now=new Date();if(!this.db.configured){const m:ChatMessage={id,channelId,author:{id:user.id,nickname:user.name},text,replyToId:body.replyToId,imageUrl:body.imageUrl,createdAt:now.toISOString()};this.messages.push(m);return m;}const r=await this.db.query<MessageRow>(`WITH inserted AS (INSERT INTO chat_messages(id,channel_id,author_id,text,reply_to_id,image_url) SELECT $1,$2,$3,$4,$5,$6 WHERE EXISTS(SELECT 1 FROM chat_channels WHERE id=$2) RETURNING *) SELECT inserted.*,u.nickname,u.avatar_url FROM inserted JOIN users u ON u.id=inserted.author_id`,[id,channelId,user.id,text,body.replyToId??null,body.imageUrl??null]);if(!r.rows[0])throw new NotFoundException("Channel not found");return this.map(r.rows[0]);}
  async remove(id:string,user:AuthUser):Promise<void>{if(!this.db.configured){const m=this.messages.find(x=>x.id===id);if(!m)throw new NotFoundException();if(m.author.id!==user.id&&!this.canModerate(user))throw new ForbiddenException();m.text="";m.deletedAt=new Date().toISOString();return;}const r=await this.db.query("UPDATE chat_messages SET text='[deleted]',image_url=NULL,deleted_at=NOW() WHERE id=$1 AND (author_id=$2 OR $3) RETURNING id",[id,user.id,this.canModerate(user)]);if(!r.rowCount)throw new ForbiddenException("Cannot delete message");}
  async block(userId:string,targetId:string,enabled:boolean):Promise<void>{if(userId===targetId)throw new BadRequestException("Cannot block yourself");if(!this.db.configured){const k=`${userId}:${targetId}`;enabled?this.blocked.add(k):this.blocked.delete(k);return;}if(enabled)await this.db.query("INSERT INTO user_blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[userId,targetId]);else await this.db.query("DELETE FROM user_blocks WHERE blocker_id=$1 AND blocked_id=$2",[userId,targetId]);}
  async report(messageId:string,userId:string,b:{category:string;comment?:string}):Promise<{id:string}>{if(!b.category)throw new BadRequestException("Category required");const id=randomUUID();if(this.db.configured){const r=await this.db.query("INSERT INTO chat_reports(id,message_id,reporter_id,category,comment,message_snapshot) SELECT $1,id,$2,$3,$4,text FROM chat_messages WHERE id=$5 RETURNING id",[id,userId,b.category,b.comment??null,messageId]);if(!r.rowCount)throw new NotFoundException("Message not found");}return{id};}
  private canModerate(u:AuthUser){return u.role==="moderator"||u.role==="platform_admin";}
  private rateLimit(id:string){const now=Date.now(),times=(this.recent.get(id)??[]).filter(t=>now-t<10000);if(times.length>=5)throw new BadRequestException("Too many messages");times.push(now);this.recent.set(id,times);}
  private map=(x:MessageRow):ChatMessage=>({id:x.id,channelId:x.channel_id,author:{id:x.author_id??"deleted",nickname:x.nickname??"Удалённый пользователь",avatarUrl:x.avatar_url??undefined},text:x.deleted_at?"":x.text,replyToId:x.reply_to_id??undefined,imageUrl:x.image_url??undefined,deletedAt:x.deleted_at?.toISOString(),createdAt:new Date(x.created_at).toISOString()});
}
