import { Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from "@nestjs/common";import type { AuthUser,TournamentSummary } from "@oyna/contracts";import { AuthGuard } from "../auth/auth.guard";import { CurrentUser } from "../auth/current-user.decorator";import { TournamentsService } from "./tournaments.service";
@Controller() export class TournamentsController{constructor(private readonly service:TournamentsService){}
@Get("tournaments")list(@Query("gameId")g?:string){return this.service.list(g)} @Get("tournaments/:id")get(@Param("id")id:string){return this.service.get(id)}
@Post("tournaments") @UseGuards(AuthGuard) create(@CurrentUser()u:AuthUser,@Body()b:Omit<TournamentSummary,"id"|"status"|"registeredCount">){return this.service.create(u,b)}
@Post("tournaments/:id/publish") @UseGuards(AuthGuard) publish(@CurrentUser()u:AuthUser,@Param("id")id:string){return this.service.publish(u,id)} @Post("tournaments/:id/register") @UseGuards(AuthGuard) register(@CurrentUser()u:AuthUser,@Param("id")id:string,@Body()b:{teamId?:string}){return this.service.register(u,id,b.teamId)}
@Post("tournaments/:id/bracket") @UseGuards(AuthGuard) bracket(@CurrentUser()u:AuthUser,@Param("id")id:string){return this.service.generateBracket(u,id)}
@Patch("tournaments/:id/registrations/:registrationId") @UseGuards(AuthGuard) review(@CurrentUser()u:AuthUser,@Param("id")id:string,@Param("registrationId")registrationId:string,@Body()b:{status:"approved"|"waitlisted"|"rejected"}){return this.service.reviewRegistration(u,id,registrationId,b.status)}
@Post("teams") @UseGuards(AuthGuard) team(@CurrentUser()u:AuthUser,@Body()b:{gameId:string;name:string;logoUrl?:string}){return this.service.createTeam(u,b)} @Post("teams/:id/invites") @UseGuards(AuthGuard) invite(@CurrentUser()u:AuthUser,@Param("id")id:string,@Body()b:{userId:string}){return this.service.invite(u,id,b.userId)}
@Patch("teams/:id/invites/me") @UseGuards(AuthGuard) respond(@CurrentUser()u:AuthUser,@Param("id")id:string,@Body()b:{accept:boolean}){return this.service.respondInvite(u.id,id,b.accept)}
@Post("matches/:id/result") @UseGuards(AuthGuard) result(@CurrentUser()u:AuthUser,@Param("id")id:string,@Body()b:{scoreA:number;scoreB:number}){return this.service.reportResult(u,id,b)} @Post("matches/:id/confirm") @UseGuards(AuthGuard) confirm(@CurrentUser()u:AuthUser,@Param("id")id:string){return this.service.confirm(u,id)} @Post("matches/:id/dispute") @UseGuards(AuthGuard) dispute(@CurrentUser()u:AuthUser,@Param("id")id:string){return this.service.confirm(u,id,true)}}
