import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import type { AuthUser, TeamSummary, TournamentMatch, TournamentSummary } from "@oyna/contracts"; import { randomUUID } from "node:crypto"; import { DatabaseService } from "../database/database.service";
import { NotificationsService } from "./notifications.service";
interface TournamentRow {id:string;club_id:string;game_id:string;name:string;description:string;rules:string;kind:"solo"|"team";capacity:4|8|16|32;status:TournamentSummary["status"];registration_starts_at:Date;registration_ends_at:Date;starts_at:Date;entry_fee_text:string|null;prize_text:string|null;registered_count:string;}
@Injectable() export class TournamentsService {
 private readonly tournaments=new Map<string,TournamentSummary>();private readonly teams=new Map<string,TeamSummary>();private readonly registrations=new Map<string,{id:string;participant:string;status:string}[]>();private readonly matches=new Map<string,TournamentMatch[]>();
 constructor(private readonly db:DatabaseService,private readonly notifications:NotificationsService){}
 async list(gameId?:string,clubId?:string):Promise<TournamentSummary[]>{if(!this.db.configured)return [...this.tournaments.values()].filter(t=>(!gameId||t.gameId===gameId)&&(!clubId||t.clubId===clubId));const r=await this.db.query<TournamentRow>(`SELECT t.*,COUNT(r.id) FILTER(WHERE r.status IN('pending','approved','waitlisted')) registered_count FROM tournaments t LEFT JOIN tournament_registrations r ON r.tournament_id=t.id WHERE ($1::text IS NULL OR t.game_id=$1) AND ($2::text IS NULL OR t.club_id=$2) AND t.status<>'draft' GROUP BY t.id ORDER BY t.starts_at`,[gameId??null,clubId??null]);return r.rows.map(this.mapTournament);}
 async get(id:string):Promise<{tournament:TournamentSummary;matches:TournamentMatch[]}>{const tournament=this.db.configured?await this.getDb(id):this.tournaments.get(id);if(!tournament)throw new NotFoundException("Tournament not found");return{tournament,matches:await this.getMatches(id)}}
 async create(user:AuthUser,b:Omit<TournamentSummary,"id"|"status"|"registeredCount">):Promise<TournamentSummary>{await this.assertClubAdmin(user,b.clubId);if(![4,8,16,32].includes(b.capacity))throw new BadRequestException("Capacity must be 4, 8, 16 or 32");if(!(Date.parse(b.registrationStartsAt)<Date.parse(b.registrationEndsAt)&&Date.parse(b.registrationEndsAt)<=Date.parse(b.startsAt)))throw new BadRequestException("Invalid tournament schedule");const t:TournamentSummary={...b,id:randomUUID(),status:"draft",registeredCount:0};if(!this.db.configured){this.tournaments.set(t.id,t);return t;}await this.db.query(`INSERT INTO tournaments(id,club_id,game_id,creator_id,name,description,rules,kind,capacity,registration_starts_at,registration_ends_at,starts_at,entry_fee_text,prize_text) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[t.id,t.clubId,t.gameId,user.id,t.name,t.description,t.rules,t.kind,t.capacity,t.registrationStartsAt,t.registrationEndsAt,t.startsAt,t.entryFeeText??null,t.prizeText??null]);return t;}
 async publish(user:AuthUser,id:string){const t=(await this.get(id)).tournament;await this.assertClubAdmin(user,t.clubId);if(t.status!=="draft")throw new ConflictException("Only drafts can be published");return this.setStatus(id,"published");}
 async createTeam(user:AuthUser,b:{gameId:string;name:string;logoUrl?:string}):Promise<TeamSummary>{if(!b.name.trim()||b.name.length>40)throw new BadRequestException("Invalid team name");const team:TeamSummary={id:randomUUID(),gameId:b.gameId,name:b.name.trim(),logoUrl:b.logoUrl,captainId:user.id,memberIds:[user.id]};if(!this.db.configured){this.teams.set(team.id,team);return team;}await this.db.transaction(async c=>{await c.query("INSERT INTO teams(id,game_id,name,logo_url,captain_id) VALUES($1,$2,$3,$4,$5)",[team.id,team.gameId,team.name,team.logoUrl??null,user.id]);await c.query("INSERT INTO team_members(team_id,user_id,status) VALUES($1,$2,'active')",[team.id,user.id]);});return team;}
 async invite(user:AuthUser,teamId:string,targetId:string):Promise<void>{const team=await this.getTeam(teamId);if(team.captainId!==user.id)throw new ForbiddenException("Captain access required");if(this.db.configured)await this.db.query("INSERT INTO team_members(team_id,user_id,status,expires_at) VALUES($1,$2,'invited',NOW()+INTERVAL '72 hours') ON CONFLICT(team_id,user_id) DO UPDATE SET status='invited',expires_at=EXCLUDED.expires_at",[teamId,targetId]);else if(!team.memberIds.includes(targetId))team.memberIds.push(targetId);await this.notifications.create(targetId,{type:"team_invite",title:"Приглашение в команду",body:`${user.name} приглашает в ${team.name}`,href:`/teams/${team.id}`});}
 async respondInvite(userId:string,teamId:string,accept:boolean):Promise<void>{if(this.db.configured){const r=await this.db.query("UPDATE team_members SET status=$3 WHERE team_id=$1 AND user_id=$2 AND status='invited' AND expires_at>NOW() RETURNING user_id",[teamId,userId,accept?"active":"declined"]);if(!r.rowCount)throw new ConflictException("Invitation is invalid or expired");}}
 async register(user:AuthUser,tournamentId:string,teamId?:string):Promise<{id:string;status:string}>{const t=(await this.get(tournamentId)).tournament;if(t.status!=="published")throw new ConflictException("Registration is closed");if(t.kind==="team"){if(!teamId)throw new BadRequestException("Team required");const team=await this.getTeam(teamId);if(team.captainId!==user.id)throw new ForbiddenException("Captain must register the team");}const status=t.registeredCount>=t.capacity?"waitlisted":"pending",id=randomUUID();if(!this.db.configured){const r=this.registrations.get(tournamentId)??[],p=teamId??user.id;if(r.some(x=>x.participant===p))throw new ConflictException("Already registered");r.push({id,participant:p,status});this.registrations.set(tournamentId,r);t.registeredCount=r.length;return{id,status};}await this.db.query("INSERT INTO tournament_registrations(id,tournament_id,user_id,team_id,status) VALUES($1,$2,$3,$4,$5)",[id,tournamentId,teamId?null:user.id,teamId??null,status]);return{id,status};}
 async reviewRegistration(user:AuthUser,tournamentId:string,registrationId:string,status:"approved"|"waitlisted"|"rejected"):Promise<void>{const t=(await this.get(tournamentId)).tournament;await this.assertClubAdmin(user,t.clubId);if(!this.db.configured){const r=this.registrations.get(tournamentId)?.find(x=>x.id===registrationId);if(!r)throw new NotFoundException("Registration not found");r.status=status;return;}const result=await this.db.query("UPDATE tournament_registrations SET status=$3 WHERE id=$1 AND tournament_id=$2 RETURNING id",[registrationId,tournamentId,status]);if(!result.rowCount)throw new NotFoundException("Registration not found");}
 async generateBracket(user:AuthUser,id:string):Promise<TournamentMatch[]>{const t=(await this.get(id)).tournament;await this.assertClubAdmin(user,t.clubId);let participants:string[];if(this.db.configured){const r=await this.db.query<{participant:string}>("SELECT COALESCE(team_id,user_id) participant FROM tournament_registrations WHERE tournament_id=$1 AND status='approved' ORDER BY created_at",[id]);participants=r.rows.map(x=>x.participant);}else participants=(this.registrations.get(id)??[]).filter(x=>x.status==="approved").map(x=>x.participant);if(participants.length!==t.capacity)throw new ConflictException(`Exactly ${t.capacity} approved participants required`);participants=this.shuffle(participants);const rounds=Math.log2(t.capacity),matches:TournamentMatch[]=[];for(let round=1;round<=rounds;round++){for(let position=0;position<t.capacity/2**round;position++)matches.push({id:randomUUID(),tournamentId:id,round,position,participantAId:round===1?participants[position*2]:undefined,participantBId:round===1?participants[position*2+1]:undefined,status:"pending"});}if(this.db.configured)await this.db.transaction(async c=>{for(const m of matches)await c.query("INSERT INTO tournament_matches(id,tournament_id,round,position,participant_a_id,participant_b_id) VALUES($1,$2,$3,$4,$5,$6)",[m.id,id,m.round,m.position,m.participantAId??null,m.participantBId??null]);await c.query("UPDATE tournaments SET status='in_progress',updated_at=NOW() WHERE id=$1",[id]);});else{this.matches.set(id,matches);t.status="in_progress";}return matches;}
 async reportResult(user:AuthUser,matchId:string,b:{scoreA:number;scoreB:number}):Promise<TournamentMatch>{if(b.scoreA===b.scoreB||b.scoreA<0||b.scoreB<0)throw new BadRequestException("A match must have one winner");if(this.db.configured){const r=await this.db.query<{tournament_id:string;participant_a_id:string;participant_b_id:string}>("SELECT tournament_id,participant_a_id,participant_b_id FROM tournament_matches WHERE id=$1",[matchId]);const m=r.rows[0];if(!m)throw new NotFoundException();const winner=b.scoreA>b.scoreB?m.participant_a_id:m.participant_b_id;await this.db.query("UPDATE tournament_matches SET score_a=$2,score_b=$3,winner_id=$4,reporter_id=$5,status='awaiting_confirmation',updated_at=NOW() WHERE id=$1",[matchId,b.scoreA,b.scoreB,winner,user.id]);return (await this.getMatches(m.tournament_id)).find(x=>x.id===matchId)!;}const m=[...this.matches.values()].flat().find(x=>x.id===matchId);if(!m)throw new NotFoundException();m.scoreA=b.scoreA;m.scoreB=b.scoreB;m.winnerId=b.scoreA>b.scoreB?m.participantAId:m.participantBId;m.status="awaiting_confirmation";return m;}
 async confirm(user:AuthUser,matchId:string,dispute=false):Promise<void>{if(!this.db.configured){const m=[...this.matches.values()].flat().find(x=>x.id===matchId);if(!m)throw new NotFoundException();m.status=dispute?"disputed":"completed";if(!dispute)this.advance(m);return;}const r=await this.db.query<{tournament_id:string;round:number;position:number;winner_id:string}>("UPDATE tournament_matches SET status=$2,updated_at=NOW() WHERE id=$1 AND status='awaiting_confirmation' RETURNING tournament_id,round,position,winner_id",[matchId,dispute?"disputed":"completed"]);if(!r.rows[0])throw new ConflictException("Result cannot be confirmed");if(!dispute){const m=r.rows[0],slot=m.position%2===0?"participant_a_id":"participant_b_id";await this.db.query(`UPDATE tournament_matches SET ${slot}=$1 WHERE tournament_id=$2 AND round=$3 AND position=$4`,[m.winner_id,m.tournament_id,m.round+1,Math.floor(m.position/2)]);}}
 private async assertClubAdmin(u:AuthUser,clubId:string){if(u.role==="platform_admin")return;if(!this.db.configured){if(u.role!=="club_admin")throw new ForbiddenException("Club admin access required");return;}const r=await this.db.query("SELECT 1 FROM club_memberships WHERE club_id=$1 AND user_id=$2 AND role='admin'",[clubId,u.id]);if(!r.rowCount)throw new ForbiddenException("Club admin access required");}
 private async getDb(id:string){const r=await this.db.query<TournamentRow>(`SELECT t.*,COUNT(r.id) FILTER(WHERE r.status IN('pending','approved','waitlisted')) registered_count FROM tournaments t LEFT JOIN tournament_registrations r ON r.tournament_id=t.id WHERE t.id=$1 GROUP BY t.id`,[id]);return r.rows[0]?this.mapTournament(r.rows[0]):undefined;}
 private async getTeam(id:string):Promise<TeamSummary>{if(!this.db.configured){const t=this.teams.get(id);if(!t)throw new NotFoundException("Team not found");return t;}const r=await this.db.query<{id:string;game_id:string;name:string;logo_url:string|null;captain_id:string;member_ids:string[]}>(`SELECT t.*,COALESCE(array_agg(m.user_id) FILTER(WHERE m.status='active'),'{}') member_ids FROM teams t LEFT JOIN team_members m ON m.team_id=t.id WHERE t.id=$1 GROUP BY t.id`,[id]);if(!r.rows[0])throw new NotFoundException("Team not found");const t=r.rows[0];return{id:t.id,gameId:t.game_id,name:t.name,logoUrl:t.logo_url??undefined,captainId:t.captain_id,memberIds:t.member_ids};}
 private async getMatches(id:string):Promise<TournamentMatch[]>{if(!this.db.configured)return this.matches.get(id)??[];const r=await this.db.query<{id:string;tournament_id:string;round:number;position:number;participant_a_id:string|null;participant_b_id:string|null;score_a:number|null;score_b:number|null;winner_id:string|null;status:TournamentMatch["status"]}>("SELECT * FROM tournament_matches WHERE tournament_id=$1 ORDER BY round,position",[id]);return r.rows.map(x=>({id:x.id,tournamentId:x.tournament_id,round:x.round,position:x.position,participantAId:x.participant_a_id??undefined,participantBId:x.participant_b_id??undefined,scoreA:x.score_a??undefined,scoreB:x.score_b??undefined,winnerId:x.winner_id??undefined,status:x.status}));}
 private async setStatus(id:string,status:TournamentSummary["status"]){if(this.db.configured)await this.db.query("UPDATE tournaments SET status=$2,updated_at=NOW() WHERE id=$1",[id,status]);else this.tournaments.get(id)!.status=status;return this.get(id);}
 private mapTournament=(x:TournamentRow):TournamentSummary=>({id:x.id,clubId:x.club_id,gameId:x.game_id,name:x.name,description:x.description,rules:x.rules,kind:x.kind,capacity:x.capacity,status:x.status,registrationStartsAt:new Date(x.registration_starts_at).toISOString(),registrationEndsAt:new Date(x.registration_ends_at).toISOString(),startsAt:new Date(x.starts_at).toISOString(),entryFeeText:x.entry_fee_text??undefined,prizeText:x.prize_text??undefined,registeredCount:Number(x.registered_count)});
 private shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
 private advance(m:TournamentMatch){const all=this.matches.get(m.tournamentId)??[],next=all.find(x=>x.round===m.round+1&&x.position===Math.floor(m.position/2));if(next){if(m.position%2===0)next.participantAId=m.winnerId;else next.participantBId=m.winnerId;}}
}
